[buildPlans.AdwaitaMono]
family = "Adwaita Mono"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false


[buildPlans.AdwaitaMono.variants.design]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "dotted"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless"
i = "serifed-asymmetric"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook"
w = "straight-flat-top-serifless"
y = "straight-turn-serifless"
long-s = "flat-hook-serifless"
lower-gamma = "straight"
lower-lambda = "tailed-turn"
lower-upsilon = "straight-serifless"
lower-chi = "semi-chancery-straight-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
asterisk = "hex-high"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold-solid-inner"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.AdwaitaMono.variants.italic]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "dotted"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
d = "toothed-serifless"
f = "flat-hook-tailed"
i = "serifed-asymmetric"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook"
w = "straight-flat-top-serifless"
u = "toothed-serifless"
y = "straight-turn-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-serifless"
lower-gamma = "straight"
lower-lambda = "tailed-turn"
lower-upsilon = "straight-serifless"
lower-chi = "semi-chancery-straight-serifless"
cyrl-ve = "standard-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"
asterisk = "hex-high"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold-solid-inner"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"


[buildPlans.AdwaitaMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.AdwaitaMono.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.AdwaitaMono.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.AdwaitaMono.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.AdwaitaMono.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.AdwaitaMono.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.AdwaitaMono.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.AdwaitaMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.AdwaitaMono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
