[buildPlans.Fourvka]
family = "Fourvka"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.Fourvka.variants]
  inherits = "ss14"

    [buildPlans.Fourvka.variants.design]
    one = "base"
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "upright-flat-serifless"
    six = "closed-contour"
    seven = "straight-serifed"
    nine = "closed-contour"
    zero = "dotted"
    capital-a = "straight-top-serifed"
    capital-b = "standard-unilateral-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-d = "standard-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-inward-serifed-hooked"
    capital-h = "top-left-serifed"
    capital-j = "serifed"
    capital-k = "symmetric-connected-top-left-serifed"
    capital-l = "motion-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "crossing"
    capital-r = "straight-top-left-serifed"
    capital-s = "serifless"
    capital-u = "toothless-corner-unilateral-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-unilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-top-serifed"
    a = "double-storey-serifless"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-serifless"
    f = "flat-hook-serifless"
    g = "single-storey-flat-hook-serifless"
    h = "straight-serifless"
    i = "serifed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "corner-hooked-serifless"
    s = "serifless"
    t = "flat-hook"
    u = "toothless-rounded-serifless"
    v = "straight-serifless"
    w = "straight-vertical-sides-serifless"
    x = "straight-serifless"
    y = "cursive-flat-hook-serifless"
    z = "straight-serifless"

    [buildPlans.Fourvka.variants.italic]
    one = "base-long-top-serif"
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-non-crossing-serifed"
    five = "upright-flat-serifed"
    six = "open-contour"
    seven = "straight-serifed-crossbar"
    eight = "crossing-asymmetric"
    nine = "open-contour"
    zero = "reverse-slashed"
    capital-a = "straight-tri-serifed"
    capital-b = "standard-bilateral-serifed"
    capital-c = "bilateral-serifed"
    capital-d = "standard-bilateral-serifed"
    capital-e = "serifed"
    capital-f = "serifed-capped"
    capital-g = "toothless-corner-inward-serifed-capped"
    capital-h = "serifed"
    capital-j = "descending-serifed"
    capital-k = "symmetric-connected-serifed"
    capital-l = "serifed"
    capital-m = "hanging-serifed"
    capital-n = "standard-serifed"
    capital-p = "open-motion-serifed"
    capital-q = "open-swash"
    capital-r = "standing-open-top-left-serifed"
    capital-s = "bilateral-serifed"
    capital-t = "motion-serifed"
    capital-u = "toothed-serifed"
    capital-v = "straight-serifed"
    capital-w = "straight-serifed"
    capital-x = "straight-bilateral-motion-serifed"
    capital-y = "straight-serifed"
    capital-z = "straight-top-serifed-with-crossbar"
    a = "single-storey-serifless"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-serifless"
    f = "diagonal-tailed"
    g = "single-storey-flat-hook-serifless"
    h = "straight-top-left-serifed"
    i = "serifed-diagonal-tailed"
    j = "diagonal-tailed-serifed"
    k = "cursive-serifless"
    l = "serifed-diagonal-tailed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "top-cut-diagonal-tailed-serifless"
    r = "corner-hooked-top-serifed"
    s = "serifless"
    t = "diagonal-tailed-asymmetric"
    u = "toothed-motion-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "curly-serifed"
    y = "cursive-motion-serifed"
    z = "straight-serifless-with-crossbar"

[buildPlans.Fourvka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Fourvka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Fourvka.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Fourvka.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.Fourvka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Fourvka.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.Fourvka.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.Fourvka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Fourvka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
