[buildPlans.Fourvka]
family = "Fourvka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Fourvka.variants]
  inherits = "ss17"

    [buildPlans.Fourvka.variants.design]
    one = "no-base"
    two = "straight-neck-serifless"
    four = "semi-open-serifless"
    five = "upright-arched-serifless"
    six = "closed-contour"
    seven = "straight-serifless"
    nine = "closed-contour"
    capital-a = "straight-top-serifed"
    capital-b = "standard-unilateral-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-d = "standard-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-inward-serifed-capped"
    capital-h = "top-left-serifed"
    capital-j = "serifed"
    capital-k = "straight-top-left-serifed"
    capital-l = "motion-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "crossing-baseline"
    capital-r = "straight-top-left-serifed"
    capital-s = "serifless"
    capital-u = "toothless-corner-unilateral-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-unilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-top-serifed"
    a = "double-storey-serifless"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-serifless"
    f = "extended"
    g = "single-storey-flat-hook-serifless"
    h = "straight-top-left-serifed"
    i = "serifed-diagonal-tailed"
    j = "diagonal-tailed-serifed"
    k = "straight-serifless"
    l = "serifed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "top-cut-diagonal-tailed-serifless"
    r = "corner-hooked-serifless"
    s = "serifless"
    t = "diagonal-tailed"
    u = "toothless-corner-serifless"
    v = "straight-serifless"
    w = "straight-vertical-sides-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"

    [buildPlans.Fourvka.variants.italic]
    one = "base"
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-serifed"
    five = "upright-arched-serifed"
    six = "open-contour"
    seven = "straight-serifless-crossbar"
    eight = "crossing-asymmetric"
    nine = "open-contour"
    zero = "reverse-slashed"
    capital-a = "straight-top-serifed"
    capital-b = "standard-unilateral-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-d = "standard-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-inward-serifed-capped"
    capital-h = "top-left-serifed"
    capital-j = "descending-serifed"
    capital-k = "straight-top-left-serifed"
    capital-l = "motion-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "asymmetric-motion-serifed"
    capital-p = "open-motion-serifed"
    capital-q = "open-swash"
    capital-r = "standing-open-top-left-serifed"
    capital-s = "serifless"
    capital-u = "toothed-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-bilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-top-serifed-with-crossbar"
    a = "single-storey-serifless"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-serifless"
    f = "diagonal-tailed"
    g = "single-storey-flat-hook-serifless"
    h = "straight-top-left-serifed"
    i = "serifed-diagonal-tailed"
    j = "diagonal-tailed-serifed"
    k = "cursive-serifless"
    l = "serifed-diagonal-tailed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "top-cut-diagonal-tailed-serifless"
    r = "corner-hooked-top-serifed"
    s = "serifless"
    t = "diagonal-tailed-asymmetric"
    u = "toothed-motion-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "curly-serifed"
    y = "cursive-motion-serifed"
    z = "straight-serifless-with-crossbar"

[buildPlans.Fourvka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Fourvka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Fourvka.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.Fourvka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Fourvka.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.Fourvka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Fourvka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
