[buildPlans.Fourvka]
family = "Fourvka"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = false
noLigation = true

[buildPlans.Fourvka.variants.design]
one = "no-base"
two = "straight-neck-serifless"
four = "semi-open-serifless"
five = "upright-arched-serifed"
six = "closed-contour"
seven = "straight-serifed"
nine = "closed-contour"
capital-a = "straight-top-serifed"
capital-b = "standard-unilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "top-left-serifed"
capital-k = "straight-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing-baseline"
capital-r = "straight-top-left-serifed"
capital-s = "unilateral-inward-serifed"
capital-u = "toothed-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-unilateral-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-hook-inward-serifed-serifless"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "toothed-top-serifed"
f = "extended"
g = "single-storey-flat-hook-serifed"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "straight-top-left-serifed"
l = "serifed-diagonal-tailed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "eared-motion-serifed"
q = "top-cut-diagonal-tailed-serifless"
r = "corner-hooked-top-serifed"
s = "unilateral-inward-serifed"
t = "hookless-asymmetric"
u = "tailed-motion-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-unilateral-motion-serifed"
y = "straight-motion-serifed"
z = "straight-top-serifed"

[buildPlans.Fourvka.variants.italic]
one = "no-base-flat-top-serif"
two = "curly-neck-serifless"
four = "closed-non-crossing-serifless"
five = "oblique-arched-serifed"
six = "open-contour"
seven = "bend-serifed-crossbar"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "slashed-split"
capital-a = "straight-top-serifed"
capital-b = "standard-unilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-inward-serifed-hookless"
capital-h = "top-left-serifed"
capital-j = "flat-hook-serifed"
capital-k = "straight-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "standing-open-top-left-and-bottom-right-serifed"
capital-s = "unilateral-inward-serifed"
capital-u = "toothed-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "curly-unilateral-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "straight-top-serifed-with-crossbar"
a = "single-storey-top-cut-serifless"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "toothed-top-serifed"
f = "diagonal-tailed-crossbar-at-x-height"
g = "double-storey"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifless"
k = "cursive-top-left-serifed"
l = "diagonal-tailed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "eared-motion-serifed"
q = "top-cut-diagonal-tailed-serifless"
r = "corner-hooked-top-serifed"
s = "unilateral-inward-serifed"
t = "hookless"
u = "tailed-motion-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "semi-chancery-curly-serifed"
y = "curly-motion-serifed"
z = "curly-top-serifed-with-crossbar"

[buildPlans.Fourvka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Fourvka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Fourvka.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Fourvka.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.Fourvka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Fourvka.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.Fourvka.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"
