name: Build AdwaitaMono

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ttfautohint
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install NPM packages
      run: npm install

    - name: Build custom Iosevka
      run: npm run build -- ttf::AdwaitaMono

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AdwaitaMono-fonts
        path: dist/
